"""
Module applicatif.

Fichier: reclamations/migrations/0001_initial.py
"""

# Generated by Django 4.2.7 on 2025-06-14 15:39

# ==================== Imports ====================
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reclamation', models.CharField(max_length=100, verbose_name='Type de réclamation')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('reponse', models.TextField(blank=True, null=True, verbose_name='Réponse')),
                ('suivi', models.TextField(blank=True, null=True, verbose_name='Suivi')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('classement', models.CharField(choices=[('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('CLOS', 'Clos'), ('REPORTE', 'Reporté'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20, verbose_name='Classement')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='Priorité')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_reception'],
            },
        ),
    ]
