"""
Module applicatif.

Fichier: reclamations/migrations/0003_reclamation_document.py
"""

# Generated by Django 4.2.7 on 2025-06-24 15:11

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_add_destinataire_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='reclamations/documents/', verbose_name='Document joint'),
        ),
    ]
