"""
Module applicatif.

Fichier: reclamations/migrations/0004_reclamation_code.py
"""

# Generated by Django 4.2.7 on 2025-07-04 17:01

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_reclamation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='code',
            field=models.CharField(blank=True, help_text='Code métier unique pour identifier la réclamation', max_length=50, null=True, unique=True),
        ),
    ]
