# Generated by Django 4.2.7 on 2025-07-09 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclamations', '0004_reclamation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_envoyees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
