"""
Module applicatif.

Fichier: reclamations/migrations/0006_alter_reclamation_created_by.py
"""

# Generated by Django 4.2.7 on 2025-07-09 12:12

# ==================== Imports ====================
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclamations', '0005_reclamation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_envoyees', to=settings.AUTH_USER_MODEL),
        ),
    ]
