"""
Module applicatif.

Fichier: reclamations/migrations/0008_reclamation_is_deleted.py
"""

# Generated by Django 5.2.3 on 2025-09-18 23:08

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_alter_reclamation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
