"""
Module applicatif.

Fichier: evenements/migrations/0001_initial.py
"""

# Generated by Django 5.2.3 on 2025-09-27 20:06

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('AID_AL_ADHA', 'عيد الأضحى'), ('AID_AL_FITR', 'عيد الفطر'), ('RAMADAN', 'رمضان'), ('MAWLID_NABAWI', 'ذكرى المولد النبوي الشريف'), ('NEW_YEAR_GREGORIAN', 'السنة الميلادية'), ('NEW_YEAR_ISLAMIC', 'السنة الهجرية')], max_length=50, unique=True)),
                ('date', models.DateField()),
                ('message', models.TextField(default='')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
            },
        ),
    ]
