"""
Module applicatif.

Fichier: evenements/migrations/0002_evenement_description_evenement_type_evenement_and_more.py
"""

# Generated by Django 4.2.7 on 2025-09-28 00:20

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('GREGORIEN', 'Grégorien'), ('ISLAMIQUE', 'Islamique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
