# Generated by Django 4.2.7 on 2026-02-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_evenement_description_evenement_type_evenement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='evenement',
            unique_together={('nom', 'date')},
        ),
    ]
