"""
Module applicatif.

Fichier: dossiers/migrations/0001_initial.py
"""

# Generated by Django 4.2.7 on 2025-06-14 15:39

# ==================== Imports ====================
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('P', 'P - Particulier'), ('S', 'S - Société'), ('F', 'F - Forfaitaire'), ('R', 'R - Radié'), ('L', 'L - Livré'), ('D', 'D - Délaissé'), ('FS', 'FS - Forfaitaire Société')], max_length=10, verbose_name='Code du dossier')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('denomination', models.CharField(max_length=200, verbose_name="Dénomination de l'entreprise")),
                ('abreviation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abréviation')),
                ('forme_juridique', models.CharField(choices=[('SARL', 'SARL - Société à Responsabilité Limitée'), ('SA', 'SA - Société Anonyme'), ('SNC', 'SNC - Société en Nom Collectif'), ('SCS', 'SCS - Société en Commandite Simple'), ('SCA', 'SCA - Société en Commandite par Actions'), ('EURL', 'EURL - Entreprise Unipersonnelle à Responsabilité Limitée'), ('SASU', 'SASU - Société par Actions Simplifiée Unipersonnelle'), ('SAS', 'SAS - Société par Actions Simplifiée'), ('EI', 'EI - Entreprise Individuelle'), ('EIRL', 'EIRL - Entreprise Individuelle à Responsabilité Limitée'), ('AUTO', 'Auto-entrepreneur'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Forme juridique')),
                ('date_creation', models.DateField(verbose_name="Date de création de l'entreprise")),
                ('secteur_activites', models.CharField(max_length=200, verbose_name="Secteur d'activités")),
                ('branche_activite', models.CharField(max_length=200, verbose_name="Branche d'activité")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'entreprise")),
                ('fixe', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,20}$')], verbose_name='Téléphone fixe')),
                ('gsm', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,20}$')], verbose_name='Téléphone mobile')),
                ('gerant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gérant')),
                ('personne_a_contacter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Personne à contacter')),
                ('if_identifiant', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identifiant Fiscal (IF)')),
                ('ice', models.CharField(blank=True, max_length=20, null=True, verbose_name="Identifiant Commun de l'Entreprise (ICE)")),
                ('tp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Taxe Professionnelle (TP)')),
                ('rc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Registre de Commerce (RC)')),
                ('cnss', models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro CNSS de l'entreprise")),
                ('declaration_tva', models.CharField(choices=[('MENSUELLE', 'TVA Mensuelle'), ('TRIMESTRIELLE', 'TVA Trimestrielle'), ('EXONEREE', 'Exonérée de la TVA')], default='EXONEREE', max_length=20, verbose_name='Déclaration à la TVA')),
                ('date_creation_dossier', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('statut', models.CharField(choices=[('EXISTANT', 'Existant'), ('RADIE', 'Radié'), ('LIVRE', 'Livré'), ('DELAISSE', 'Délaissé')], default='EXISTANT', max_length=20, verbose_name='Statut du dossier')),
                ('comptable_traitant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='comptables.comptable', verbose_name='Comptable traitant')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['denomination'],
                'unique_together': {('denomination', 'comptable_traitant')},
            },
        ),
    ]
