# Generated by Django 4.2.7 on 2025-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='designation',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='code',
            field=models.CharField(choices=[('P', 'P - Particulier'), ('S', 'S - Société'), ('F', 'F - Forfaitaire'), ('R', 'R - Radié'), ('L', 'L - Livré'), ('D', 'D - Délaissé')], max_length=10, verbose_name='Code du dossier'),
        ),
    ]
