"""
Module applicatif.

Fichier: dossiers/migrations/0003_dossier_client.py
"""

# Generated by Django 4.2.7 on 2025-06-20 13:52

# ==================== Imports ====================
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0002_remove_dossier_designation_alter_dossier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
