# Generated by Django 4.2.7 on 2025-06-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_dossier_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='statut_fiscal',
            field=models.CharField(blank=True, choices=[('A_JOUR', 'À jour'), ('EN_RETARD', 'En retard'), ('NON_COMMUNIQUE', 'Non communiqué')], default='NON_COMMUNIQUE', max_length=20, null=True, verbose_name='Statut fiscal'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='code',
            field=models.CharField(choices=[('P', 'P - Personne physique'), ('S', 'S - Société'), ('F', 'F - Forfaitaire'), ('R', 'R - Radié'), ('L', 'L - Livré'), ('D', 'D - Délaissé')], max_length=10, verbose_name='Code du dossier'),
        ),
    ]
