"""
Module applicatif.

Fichier: dossiers/migrations/0005_auto_20250627_1350.py
"""

# Generated by Django 4.2.7 on 2025-06-27 11:50

# ==================== Imports ====================
from django.db import migrations


# ==================== Fonctions ====================
def set_actif_true(apps, schema_editor):
    Dossier = apps.get_model('dossiers', 'Dossier')
    Dossier.objects.filter(actif=False).update(actif=True)
    Dossier.objects.all().update(actif=True)

# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_dossier_statut_fiscal_alter_dossier_code'),
    ]

    operations = [
        migrations.RunPython(set_actif_true),
    ]
