"""
Module applicatif.

Fichier: dossiers/migrations/0006_alter_dossier_forme_juridique.py
"""

# Generated by Django 4.2.7 on 2025-07-04 17:01

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_auto_20250627_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='forme_juridique',
            field=models.CharField(choices=[('SARL', 'SARL - Société à Responsabilité Limitée'), ('SA', 'SA - Société Anonyme'), ('SNC', 'SNC - Société en Nom Collectif'), ('SCS', 'SCS - Société en Commandite Simple'), ('SCA', 'SCA - Société en Commandite par Actions'), ('EURL', 'EURL - Entreprise Unipersonnelle à Responsabilité Limitée'), ('SASU', 'SASU - Société par Actions Simplifiée Unipersonnelle'), ('SAS', 'SAS - Société par Actions Simplifiée'), ('EI', 'EI - Entreprise Individuelle'), ('PP', 'PP - Personne Physique'), ('EIRL', 'EIRL - Entreprise Individuelle à Responsabilité Limitée'), ('AUTO', 'Auto-entrepreneur'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Forme juridique'),
        ),
    ]
