# Generated by Django 4.2.7 on 2025-07-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_client_user'),
        ('dossiers', '0006_alter_dossier_forme_juridique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_client', to='utilisateurs.client', verbose_name='Client'),
        ),
    ]
