"""
Module applicatif.

Fichier: dossiers/migrations/0008_dossier_cree_par.py
"""

# Generated by Django 4.2.7 on 2025-07-15 11:18

# ==================== Imports ====================
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0008_remove_comptable_dummy_field'),
        ('dossiers', '0007_alter_dossier_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to='comptables.comptable'),
        ),
    ]
