"""
Module applicatif.

Fichier: dossiers/migrations/0009_alter_dossier_cree_par.py
"""

# Generated by Django 4.2.7 on 2025-07-15 11:35

# ==================== Imports ====================
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0008_dossier_cree_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
