# Generated by Django 4.2.7 on 2025-07-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_alter_dossier_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='annee_extraite_pdf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
