"""
Module applicatif.

Fichier: dossiers/migrations/0010_dossier_annee_extraite_pdf.py
"""

# Generated by Django 4.2.7 on 2025-07-24 17:12

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_alter_dossier_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='annee_extraite_pdf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
