# Generated by Django 4.2.7 on 2025-08-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_dossier_annee_extraite_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name="Date de création de l'entreprise"),
        ),
    ]
