"""
Module applicatif.

Fichier: dossiers/migrations/0012_alter_dossier_comptable_traitant.py
"""

# Generated by Django 5.2.3 on 2025-09-02 22:33

# ==================== Imports ====================
import django.db.models.deletion
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0008_remove_comptable_dummy_field'),
        ('dossiers', '0011_alter_dossier_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='comptable_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='comptables.comptable', verbose_name='Comptable traitant'),
        ),
    ]
