"""
Module applicatif.

Fichier: dossiers/migrations/0013_dossier_is_deleted.py
"""

# Generated by Django 5.2.3 on 2025-09-18 23:38

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0012_alter_dossier_comptable_traitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
