"""
Module applicatif.

Fichier: dossiers/migrations/0014_auto_20250920_2150.py
"""

# Generated by Django 5.2.3 on 2025-09-20 19:50

# ==================== Imports ====================
from django.db import migrations

# ==================== Fonctions ====================
def update_dossier_is_deleted(apps, schema_editor):
    Dossier = apps.get_model('dossiers', 'Dossier')
    for dossier in Dossier.objects.all():
        if dossier.code in ['R', 'L', 'D']:
            dossier.is_deleted = True
        else:
            dossier.is_deleted = False
        dossier.save(update_fields=['is_deleted'])

# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0013_dossier_is_deleted'),
    ]

    operations = [
        migrations.RunPython(update_dossier_is_deleted, migrations.RunPython.noop),
    ]
