"""
Module applicatif.

Fichier: dossiers/migrations/0015_dossier_dernier_rappel_tva.py
"""

# Generated by Django 4.2.7 on 2025-09-28 00:13

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0014_auto_20250920_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='dernier_rappel_tva',
            field=models.DateField(blank=True, null=True, verbose_name='Date du dernier rappel TVA'),
        ),
    ]
