# Generated by Django 4.2.7 on 2025-06-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='tel_personnel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
