"""
Module applicatif.

Fichier: utilisateurs/migrations/0004_alter_client_nom_entreprise.py
"""

# Generated by Django 4.2.7 on 2025-07-18 22:40

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
