"""
Module applicatif.

Fichier: utilisateurs/migrations/0005_utilisateur_est_celebrite.py
"""

# Generated by Django 4.2.7 on 2025-09-28 00:02

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_client_nom_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_celebrite',
            field=models.BooleanField(default=False, verbose_name='Est une célébrité'),
        ),
    ]
