# Generated by Django 4.2.7 on 2025-06-14 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Matricule unique du comptable', max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('cnss', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro CNSS doit contenir entre 8 et 12 chiffres', regex='^\\d{8,12}$')], verbose_name='Numéro CNSS')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,20}$')], verbose_name='Téléphone principal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email principal')),
                ('email_personnel', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email personnel')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('nbre_pm', models.IntegerField(default=0, help_text='Calculé automatiquement', verbose_name='Nombre de dossiers PM')),
                ('nbre_et', models.IntegerField(default=0, help_text='Calculé automatiquement', verbose_name='Nombre de dossiers ET')),
                ('nbre_personn', models.IntegerField(default=0, help_text='Calculé automatiquement', verbose_name='Nombre de personnes')),
                ('nbre_bureau', models.IntegerField(default=0, help_text='Calculé automatiquement', verbose_name='Nombre de bureaux')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Comptable',
                'verbose_name_plural': 'Comptables',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
