# Generated by Django 4.2.7 on 2025-06-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptable',
            old_name='matricule',
            new_name='immatricule',
        ),
    ]
