"""
Module applicatif.

Fichier: comptables/migrations/0002_rename_matricule_comptable_immatricule.py
"""

# Generated by Django 4.2.7 on 2025-06-14 16:36

# ==================== Imports ====================
from django.db import migrations


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptable',
            old_name='matricule',
            new_name='immatricule',
        ),
    ]
