# Generated by Django 4.2.7 on 2025-06-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0002_rename_matricule_comptable_immatricule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptable',
            old_name='immatricule',
            new_name='matricule',
        ),
    ]
