"""
Module applicatif.

Fichier: comptables/migrations/0003_rename_immatricule_comptable_matricule.py
"""

# Generated by Django 4.2.7 on 2025-06-16 21:06

# ==================== Imports ====================
from django.db import migrations


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0002_rename_matricule_comptable_immatricule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptable',
            old_name='immatricule',
            new_name='matricule',
        ),
    ]
