"""
Module applicatif.

Fichier: comptables/migrations/0005_comptable_tel_personnel.py
"""

# Generated by Django 4.2.7 on 2025-06-19 12:42

# ==================== Imports ====================
import django.core.validators
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0004_create_groups_and_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptable',
            name='tel_personnel',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,20}$')], verbose_name='Téléphone personnel'),
        ),
    ]
