# Generated by Django 4.2.7 on 2025-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0006_auto_20250624_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptable',
            name='dummy_field',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='comptable',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
        migrations.AlterField(
            model_name='comptable',
            name='matricule',
            field=models.CharField(blank=True, help_text='Matricule unique du comptable', max_length=20, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
