"""
Module applicatif.

Fichier: comptables/migrations/0008_remove_comptable_dummy_field.py
"""

# Generated by Django 4.2.7 on 2025-06-24 11:22

# ==================== Imports ====================
from django.db import migrations


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0007_comptable_dummy_field_comptable_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptable',
            name='dummy_field',
        ),
    ]
