# Generated by Django 4.2.7 on 2025-06-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0007_comptable_dummy_field_comptable_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptable',
            name='dummy_field',
        ),
    ]
