"""
Module applicatif.

Fichier: comptables/migrations/0009_comptable_is_deleted.py
"""

# Generated by Django 5.2.3 on 2025-09-19 00:26

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('comptables', '0008_remove_comptable_dummy_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
