# Generated by Django 4.2.7 on 2025-06-14 15:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('jan', models.BooleanField(default=False, verbose_name='Janvier')),
                ('fev', models.BooleanField(default=False, verbose_name='Février')),
                ('mars', models.BooleanField(default=False, verbose_name='Mars')),
                ('avril', models.BooleanField(default=False, verbose_name='Avril')),
                ('mai', models.BooleanField(default=False, verbose_name='Mai')),
                ('juin', models.BooleanField(default=False, verbose_name='Juin')),
                ('juillet', models.BooleanField(default=False, verbose_name='Juillet')),
                ('aout', models.BooleanField(default=False, verbose_name='Août')),
                ('sep', models.BooleanField(default=False, verbose_name='Septembre')),
                ('oct', models.BooleanField(default=False, verbose_name='Octobre')),
                ('nov', models.BooleanField(default=False, verbose_name='Novembre')),
                ('dec', models.BooleanField(default=False, verbose_name='Décembre')),
                ('t1', models.BooleanField(default=False, verbose_name='1er trimestre')),
                ('t2', models.BooleanField(default=False, verbose_name='2ème trimestre')),
                ('t3', models.BooleanField(default=False, verbose_name='3ème trimestre')),
                ('t4', models.BooleanField(default=False, verbose_name='4ème trimestre')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_tva', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Suivi TVA',
                'verbose_name_plural': 'Suivis TVA',
                'ordering': ['-annee'],
                'unique_together': {('dossier', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='SuiviForfaitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('code_pp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code PP')),
                ('declaration_annuelle', models.BooleanField(default=False, verbose_name='Déclaration annuelle effectuée')),
                ('paiement_annuel', models.BooleanField(default=False, verbose_name='Paiement annuel effectué')),
                ('a1', models.BooleanField(default=False, verbose_name='1er acompte payé')),
                ('a2', models.BooleanField(default=False, verbose_name='2ème acompte payé')),
                ('a3', models.BooleanField(default=False, verbose_name='3ème acompte payé')),
                ('a4', models.BooleanField(default=False, verbose_name='4ème acompte payé')),
                ('ir_9421', models.BooleanField(default=False, verbose_name='IR 9421 payé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_forfaitaire', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Suivi forfaitaire',
                'verbose_name_plural': 'Suivis forfaitaires',
                'ordering': ['-annee'],
                'unique_together': {('dossier', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='DepotBilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_exercice', models.IntegerField(verbose_name="Année d'exercice")),
                ('date_depot', models.DateField(blank=True, null=True, verbose_name='Date de dépôt')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('DEPOSE', 'Déposé'), ('RETARD', 'En retard'), ('EXEMPTE', 'Exempté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots_bilan', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Dépôt de bilan',
                'verbose_name_plural': 'Dépôts de bilans',
                'ordering': ['-annee_exercice'],
                'unique_together': {('dossier', 'annee_exercice')},
            },
        ),
        migrations.CreateModel(
            name='CMIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('montant_ir', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant IR')),
                ('montant_cm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant CM')),
                ('complement_ir', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Complément IR')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_ir', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'CM et IR',
                'verbose_name_plural': 'CM et IR',
                'ordering': ['-annee'],
                'unique_together': {('dossier', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Acompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant total')),
                ('regularisation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Régularisation')),
                ('a1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='1er acompte')),
                ('a2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='2ème acompte')),
                ('a3', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3ème acompte')),
                ('a4', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='4ème acompte')),
                ('is_montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant IS')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomptes', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Acompte',
                'verbose_name_plural': 'Acomptes',
                'ordering': ['-annee'],
                'unique_together': {('dossier', 'annee')},
            },
        ),
    ]
