"""
Module applicatif.

Fichier: fiscal/migrations/0002_alter_suiviforfaitaire_options_and_more.py
"""

# Generated by Django 4.2.7 on 2025-07-04 13:17

# ==================== Imports ====================
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_auto_20250627_1350'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suiviforfaitaire',
            options={'ordering': ['-annee'], 'verbose_name': 'Suivi Forfaitaire', 'verbose_name_plural': 'Suivis Forfaitaires'},
        ),
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='code_pp',
        ),
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='ir_9421',
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='acompte_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='1er Acompte'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='acompte_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='2ème Acompte'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='acompte_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3ème Acompte'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='acompte_4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='4ème Acompte'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code Forfaitaire'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='code_9421',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code 9421'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='ir',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code IR'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='pp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Référence PP'),
        ),
        migrations.AlterField(
            model_name='suiviforfaitaire',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_forfaitaires', to='dossiers.dossier', verbose_name='Dossier'),
        ),
        migrations.RunSQL(
            sql="""
DO $$
BEGIN
IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='fiscal_suiviforfaitaire'
      AND column_name='paiement_annuel'
      AND data_type='boolean'
) THEN
    ALTER TABLE fiscal_suiviforfaitaire
    ALTER COLUMN paiement_annuel
    TYPE numeric(12,2)
    USING CASE WHEN paiement_annuel THEN 1 ELSE 0 END;
END IF;
END $$;
""",
            reverse_sql="""
DO $$
BEGIN
IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='fiscal_suiviforfaitaire'
      AND column_name='paiement_annuel'
      AND data_type='numeric'
) THEN
    ALTER TABLE fiscal_suiviforfaitaire
    ALTER COLUMN paiement_annuel
    TYPE boolean
    USING paiement_annuel <> 0;
END IF;
END $$;
"""
        ),
    ]
