"""
Module applicatif.

Fichier: fiscal/migrations/0003_remove_suiviforfaitaire_declaration_annuelle.py
"""

# Generated by Django 4.2.7 on 2025-07-04 17:01

# ==================== Imports ====================
from django.db import migrations


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_alter_suiviforfaitaire_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='declaration_annuelle',
        ),
    ]
