# Generated by Django 4.2.7 on 2025-07-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_alter_suiviforfaitaire_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suiviforfaitaire',
            name='declaration_annuelle',
        ),
    ]
