"""
Module applicatif.

Fichier: fiscal/migrations/0004_acompte_code_cmir_code_depotbilan_code_suivitva_code.py
"""

# Generated by Django 4.2.7 on 2025-07-05 19:21

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_remove_suiviforfaitaire_declaration_annuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompte',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cmir',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='depotbilan',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code Dépot Bilan'),
        ),
        migrations.AddField(
            model_name='suivitva',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
