"""
Module applicatif.

Fichier: fiscal/migrations/0005_alter_acompte_montant.py
"""

# Generated by Django 4.2.7 on 2025-07-15 11:18

# ==================== Imports ====================
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_acompte_code_cmir_code_depotbilan_code_suivitva_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompte',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant total'),
        ),
    ]
