"""
Module applicatif.

Fichier: fiscal/migrations/0006_acompte_is_deleted_cmir_is_deleted_and_more.py
"""

# Generated by Django 5.2.3 on 2025-09-18 23:42

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_alter_acompte_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompte',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='cmir',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='depotbilan',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='suiviforfaitaire',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='suivitva',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
