# Generated by Django 4.2.7 on 2025-06-14 15:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant mensuel')),
                ('montant_trimestriel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant trimestriel')),
                ('montant_annuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant annuel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='honoraire', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Honoraire',
                'verbose_name_plural': 'Honoraires',
            },
        ),
        migrations.CreateModel(
            name='ReglementHonoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reglement', models.DateField(verbose_name='Date du règlement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant réglé')),
                ('type_reglement', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('PV', 'PV (Procès-Verbal)')], max_length=20, verbose_name='Type de règlement')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], default='CHEQUE', max_length=20, verbose_name='Mode de paiement')),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de pièce (chèque, virement, etc.)')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('honoraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='honoraires.honoraire', verbose_name='Honoraire')),
            ],
            options={
                'verbose_name': "Règlement d'honoraire",
                'verbose_name_plural': "Règlements d'honoraires",
                'ordering': ['-date_reglement'],
            },
        ),
        migrations.CreateModel(
            name='HonorairePV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pv', models.DateField(verbose_name='Date du PV')),
                ('type_pv', models.CharField(max_length=100, verbose_name='Type de PV')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant du PV')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('FACTURE', 'Facturé'), ('REGLE', 'Réglé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honoraires_pv', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Honoraire PV',
                'verbose_name_plural': 'Honoraires PV',
                'ordering': ['-date_pv'],
            },
        ),
    ]
