"""
Module applicatif.

Fichier: honoraires/migrations/0002_honoraire_date_echeance_honoraire_statut_reglement_and_more.py
"""

# Generated by Django 4.2.7 on 2025-06-20 14:19

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honoraire',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AddField(
            model_name='honoraire',
            name='statut_reglement',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_RETARD', 'En retard'), ('PAYE', 'Payé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut du règlement'),
        ),
        migrations.AddField(
            model_name='reglementhonoraire',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AddField(
            model_name='reglementhonoraire',
            name='statut_reglement',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_RETARD', 'En retard'), ('PAYE', 'Payé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut du règlement'),
        ),
    ]
