# Generated by Django 4.2.7 on 2025-06-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0002_honoraire_date_echeance_honoraire_statut_reglement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honorairepv',
            options={'verbose_name': 'Honoraire PV', 'verbose_name_plural': 'Honoraires PV'},
        ),
        migrations.AlterModelOptions(
            name='reglementhonoraire',
            options={'verbose_name': "Règlement d'honoraire"},
        ),
        migrations.RemoveField(
            model_name='honorairepv',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='honorairepv',
            name='date_pv',
        ),
        migrations.RemoveField(
            model_name='honorairepv',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='honorairepv',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='honorairepv',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='honorairepv',
            name='type_pv',
        ),
        migrations.AddField(
            model_name='honorairepv',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='honorairepv',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='honoraire',
            name='statut_reglement',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_RETARD', 'En retard'), ('PAYE', 'Payé')], default='EN_ATTENTE', max_length=50, verbose_name='Statut du règlement'),
        ),
        migrations.AlterField(
            model_name='honorairepv',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='honorairepv',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglementhonoraire',
            name='type_reglement',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=50, verbose_name='Type de règlement'),
        ),
        migrations.CreateModel(
            name='ReglementHonorairePV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reglement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_reglement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre'), ('PRELEVEMENT', 'Prélèvement'), ('VIREMENT_BANCAIRE', 'Virement Bancaire'), ('CARTE_CREDIT', 'Carte de Crédit'), ('AUTRE_MOYEN', 'Autre Moyen')], max_length=50, verbose_name='Type de règlement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('honoraire_pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglement_pv', to='honoraires.honorairepv')),
            ],
            options={
                'verbose_name': 'Règlement Honoraire PV',
                'verbose_name_plural': 'Règlements Honoraires PV',
                'ordering': ['-date_reglement'],
            },
        ),
    ]
