# Generated by Django 4.2.7 on 2025-06-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_auto_20250627_1350'),
        ('honoraires', '0003_alter_honorairepv_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honorairepv',
            name='code',
        ),
        migrations.AddField(
            model_name='honorairepv',
            name='dossier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honoraire_pvs', to='dossiers.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='reglementhonoraire',
            name='honoraire_pv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='honoraires.honorairepv'),
        ),
    ]
