# Generated by Django 4.2.7 on 2025-07-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_auto_20250627_1350'),
        ('honoraires', '0004_remove_honorairepv_code_honorairepv_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honoraire',
            name='dossier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honoraire', to='dossiers.dossier', verbose_name='Dossier'),
        ),
    ]
