"""
Module applicatif.

Fichier: honoraires/migrations/0006_honoraire_code_honorairepv_code.py
"""

# Generated by Django 4.2.7 on 2025-07-05 19:21

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0005_alter_honoraire_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='honoraire',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='honorairepv',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
