"""
Module applicatif.

Fichier: honoraires/migrations/0007_alter_reglementhonoraire_honoraire.py
"""

# Generated by Django 4.2.7 on 2025-07-07 11:16

# ==================== Imports ====================
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0006_honoraire_code_honorairepv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementhonoraire',
            name='honoraire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='honoraires.honoraire', verbose_name='Honoraire'),
        ),
    ]
