"""
Module applicatif.

Fichier: honoraires/migrations/0008_alter_reglementhonoraire_honoraire_and_more.py
"""

# Generated by Django 4.2.7 on 2025-07-07 13:08

# ==================== Imports ====================
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0007_alter_reglementhonoraire_honoraire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementhonoraire',
            name='honoraire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='honoraires.honoraire', verbose_name='Honoraire'),
        ),
        migrations.AlterField(
            model_name='reglementhonoraire',
            name='honoraire_pv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglement_pv', to='honoraires.honorairepv'),
        ),
        migrations.AlterField(
            model_name='reglementhonoraire',
            name='type_reglement',
            field=models.CharField(blank=True, choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=50, null=True, verbose_name='Type de règlement'),
        ),
        migrations.AlterField(
            model_name='reglementhonorairepv',
            name='honoraire_pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_honoraire_pv', to='honoraires.honorairepv'),
        ),
    ]
