# Generated by Django 4.2.7 on 2025-07-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0008_alter_reglementhonoraire_honoraire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementhonoraire',
            name='honoraire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='honoraires.honoraire', verbose_name='Honoraire'),
        ),
    ]
