"""
Module applicatif.

Fichier: honoraires/migrations/0010_honoraire_is_deleted.py
"""

# Generated by Django 5.2.3 on 2025-09-19 00:25

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0009_alter_reglementhonoraire_honoraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='honoraire',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
