"""
Module applicatif.

Fichier: honoraires/migrations/0011_honoraire_description_alter_honoraire_is_deleted_and_more.py
"""

# Generated by Django 5.2.3 on 2025-09-19 14:09

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('honoraires', '0010_honoraire_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='honoraire',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='honoraire',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='reglementhonoraire',
            name='type_reglement',
            field=models.CharField(blank=True, choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIELLE', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=50, null=True, verbose_name='Type de règlement'),
        ),
    ]
