# Generated by Django 4.2.7 on 2025-06-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuridiqueCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ordre')),
                ('forme', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forme')),
                ('certificat_negatif', models.BooleanField(default=False, verbose_name='Certificat négatif')),
                ('date_certificat_negatif', models.DateField(blank=True, null=True, verbose_name='Date certificat négatif')),
                ('statuts', models.BooleanField(default=False, verbose_name='Statuts')),
                ('date_statuts', models.DateField(blank=True, null=True, verbose_name='Date statuts')),
                ('contrat_bail', models.BooleanField(default=False, verbose_name='Contrat de bail')),
                ('date_contrat_bail', models.DateField(blank=True, null=True, verbose_name='Date contrat de bail')),
                ('tp', models.BooleanField(default=False, verbose_name='TP (Taxe Professionnelle)')),
                ('date_tp', models.DateField(blank=True, null=True, verbose_name='Date TP')),
                ('rc', models.BooleanField(default=False, verbose_name='RC (Registre de Commerce)')),
                ('date_rc', models.DateField(blank=True, null=True, verbose_name='Date RC')),
                ('numero_rc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro RC')),
                ('cnss', models.BooleanField(default=False, verbose_name='CNSS')),
                ('date_cnss', models.DateField(blank=True, null=True, verbose_name='Date CNSS')),
                ('numero_cnss', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNSS')),
                ('al', models.BooleanField(default=False, verbose_name='AL (Autorisation de Location)')),
                ('date_al', models.DateField(blank=True, null=True, verbose_name='Date AL')),
                ('bo', models.BooleanField(default=False, verbose_name='BO (Bulletin Officiel)')),
                ('date_bo', models.DateField(blank=True, null=True, verbose_name='Date BO')),
                ('rq', models.BooleanField(default=False, verbose_name='RQ (Registre de Qualité)')),
                ('date_rq', models.DateField(blank=True, null=True, verbose_name='Date RQ')),
                ('statut_global', models.CharField(choices=[('EN_COURS', 'En cours'), ('COMPLETE', 'Complète'), ('EN_ATTENTE', 'En attente'), ('BLOQUEE', 'Bloquée')], default='EN_COURS', max_length=20, verbose_name='Statut global')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='juridique_creation', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Juridique - Création',
                'verbose_name_plural': 'Juridiques - Créations',
            },
        ),
        migrations.CreateModel(
            name='EvenementJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION_STATUTS', 'Modification des statuts'), ('AUGMENTATION_CAPITAL', 'Augmentation de capital'), ('REDUCTION_CAPITAL', 'Réduction de capital'), ('CHANGEMENT_GERANT', 'Changement de gérant'), ('CHANGEMENT_SIEGE', 'Changement de siège'), ('DISSOLUTION', 'Dissolution'), ('LIQUIDATION', 'Liquidation'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Type d'événement")),
                ('date_evenement', models.DateField(verbose_name="Date de l'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('formalites_requises', models.TextField(blank=True, null=True, verbose_name='Formalités requises')),
                ('formalites_effectuees', models.TextField(blank=True, null=True, verbose_name='Formalités effectuées')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_juridiques', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Événement juridique',
                'verbose_name_plural': 'Événements juridiques',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='DocumentJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('STATUTS', 'Statuts'), ('PV_AG', 'PV Assemblée Générale'), ('PV_CONSEIL', "PV Conseil d'Administration"), ('CONTRAT', 'Contrat'), ('BAIL', 'Bail'), ('CERTIFICAT', 'Certificat'), ('AUTORISATION', 'Autorisation'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('nom_document', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_document', models.DateField(verbose_name='Date du document')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents_juridiques/', verbose_name='Fichier')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('FINALISE', 'Finalisé'), ('SIGNE', 'Signé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_juridiques', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document juridique',
                'verbose_name_plural': 'Documents juridiques',
                'ordering': ['-date_document'],
            },
        ),
    ]
