"""
Module applicatif.

Fichier: juridique/migrations/0002_documentjuridique_code_evenementjuridique_code_and_more.py
"""

# Generated by Django 4.2.7 on 2025-07-05 19:21

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('juridique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentjuridique',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evenementjuridique',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='juridiquecreation',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
