# Generated by Django 4.2.7 on 2025-12-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridique', '0002_documentjuridique_code_evenementjuridique_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentjuridique',
            options={'ordering': ['-date_document'], 'verbose_name': 'Document Juridique', 'verbose_name_plural': 'Documents Juridiques'},
        ),
        migrations.AlterModelOptions(
            name='evenementjuridique',
            options={'ordering': ['-date_evenement'], 'verbose_name': 'Événement Juridique', 'verbose_name_plural': 'Événements Juridiques'},
        ),
        migrations.RemoveField(
            model_name='evenementjuridique',
            name='formalites_effectuees',
        ),
        migrations.RemoveField(
            model_name='evenementjuridique',
            name='formalites_requises',
        ),
        migrations.AddField(
            model_name='documentjuridique',
            name='numero_document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de document'),
        ),
        migrations.AddField(
            model_name='evenementjuridique',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='documentjuridique',
            name='date_document',
            field=models.DateField(blank=True, null=True, verbose_name='Date du document'),
        ),
        migrations.AlterField(
            model_name='documentjuridique',
            name='nom_document',
            field=models.CharField(max_length=255, verbose_name='Nom du document'),
        ),
        migrations.AlterField(
            model_name='documentjuridique',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Archivé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='documentjuridique',
            name='type_document',
            field=models.CharField(choices=[('CONTRAT', 'Contrat'), ('PROCES_VERBAL', 'Procès-verbal'), ('ATTESTATION', 'Attestation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='evenementjuridique',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evenementjuridique',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('REALISE', 'Réalisé'), ('ANNULE', 'Annulé'), ('REPORTE', 'Reporté')], default='PLANIFIE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='evenementjuridique',
            name='type_evenement',
            field=models.CharField(choices=[('ASSEMBLEE_GENERALE', 'Assemblée Générale'), ('CONSEIL_ADMINISTRATION', "Conseil d'Administration"), ('DEPOT_COMPTES', 'Dépôt des comptes'), ('MODIFICATION_STATUTS', 'Modification des statuts'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name="Type d'événement"),
        ),
    ]
