"""
Module applicatif.

Fichier: cabinet/migrations/0001_initial.py
"""

# Generated by Django 4.2.7 on 2025-06-18 11:25

# ==================== Imports ====================
from django.db import migrations


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
