"""
Module applicatif.

Fichier: cabinet/migrations/0004_document_texte_extrait.py
"""

# Generated by Django 4.2.7 on 2025-07-22 08:44

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='texte_extrait',
            field=models.TextField(blank=True, null=True),
        ),
    ]
