# Generated by Django 4.2.7 on 2025-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='texte_extrait',
            field=models.TextField(blank=True, null=True),
        ),
    ]
