"""
Module applicatif.

Fichier: cabinet/migrations/0005_document_cree_par.py
"""

# Generated by Django 4.2.7 on 2025-07-24 00:40

# ==================== Imports ====================
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet', '0004_document_texte_extrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
