"""
Module applicatif.

Fichier: cabinet/migrations/0009_alter_document_options_remove_document_cree_par_and_more.py
"""

# Generated by Django 4.2.7 on 2025-07-24 00:50

# ==================== Imports ====================
from django.db import migrations


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_document_cree_par'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.RemoveField(
            model_name='document',
            name='cree_par',
        ),
       
    ]
