# Generated by Django 4.2.7 on 2025-07-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_document_cree_par'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.RemoveField(
            model_name='document',
            name='cree_par',
        ),
       
    ]
