"""
Module applicatif.

Fichier: cabinet/migrations/0010_document_date_creation.py
"""

# Generated by Django 4.2.7 on 2025-07-24 09:32

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_alter_document_options_remove_document_cree_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
