"""
Module applicatif.

Fichier: cabinet/migrations/0011_alter_document_date_creation.py
"""

# Generated by Django 4.2.7 on 2025-07-24 09:41

# ==================== Imports ====================
from django.db import migrations, models


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_document_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
