"""
Module applicatif.

Fichier: cabinet/migrations/0012_remove_document_date_creation.py
"""

# Generated by Django 4.2.7 on 2025-07-24 09:48

# ==================== Imports ====================
from django.db import migrations


# ==================== Classes ====================
class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_alter_document_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_creation',
        ),
    ]
