# Generated by Django 4.2.7 on 2025-07-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_alter_document_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_creation',
        ),
    ]
